FROM maven:3.8.8-eclipse-temurin AS maven_upstream

FROM jdk:1.8.0_151

RUN apt-get update \
  && apt-get install -y openssh-client --no-install-recommends \
  && rm -rf /var/lib/apt/lists/*

ENV MAVEN_HOME=/usr/share/maven

COPY --from=maven_upstream ${MAVEN_HOME} ${MAVEN_HOME}
COPY --from=maven_upstream /usr/local/bin/mvn-entrypoint.sh /usr/local/bin/mvn-entrypoint.sh

RUN ln -s ${MAVEN_HOME}/bin/mvn /usr/bin/mvn
ARG USER_HOME_DIR="/root"
ENV MAVEN_CONFIG="$USER_HOME_DIR/.m2"

ENTRYPOINT ["/usr/local/bin/mvn-entrypoint.sh"]
CMD ["mvn"]