FROM maven:3.8.8-eclipse-temurin AS maven_upstream

FROM jdk:1.8.0_191

RUN apt-get update \
  && apt-get install -y openssh-client --no-install-recommends \
  && rm -rf /var/lib/apt/lists/*

ENV MAVEN_HOME=/usr/local/maven
ENV PATH=$MAVEN_HOME/bin:$PATH

COPY --from=maven_upstream /usr/share/maven ${MAVEN_HOME}

RUN ln -s ${MAVEN_HOME}/bin/mvn /usr/bin/mvn

WORKDIR /workspace

RUN java -version && mvn -v

CMD ["mvn"]
