FROM debian:bookworm-slim

ENV DEBIAN_FRONTEND=noninteractive \
    LANG="en_US.UTF-8" \
    TZ=Asia/Shanghai \
    JAVA_HOME=/usr/local/jdk \
    PATH=/usr/local/jdk/bin:$PATH \
    JAVA_TOOL_OPTIONS="-XX:+UseContainerSupport -XX:MaxRAMPercentage=75.0 -XX:InitialRAMPercentage=75.0 -XX:MinRAMPercentage=75.0"

ARG APT_MIRROR=mirrors.aliyun.com

COPY ./fonts/simsun.ttc /usr/share/fonts/

RUN sed -i "s@http://deb.debian.org@http://${APT_MIRROR}@g" /etc/apt/sources.list.d/debian.sources \
    && sed -i "s@http://security.debian.org/debian-security@http://${APT_MIRROR}/debian-security@g" /etc/apt/sources.list.d/debian.sources \
    && apt-get update && apt-get install -y --no-install-recommends \
    ca-certificates \
    tzdata \
    fontconfig \
    libfreetype6 \
    && ln -fs /usr/share/zoneinfo/${TZ} /etc/localtime \
    && echo $TZ > /etc/timezone \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

#ADD jdk1.8.0_191.tar.gz /usr/local/
#RUN mv /usr/local/jdk1.8.0_191 /usr/local/jdk
COPY jdk1.8.0_191 /usr/local/jdk

RUN java -version

CMD ["bash"]
